### PR TITLE
Add `APPDIR_FORCE_BUNDLE_RUNTIME`

### LINKED ISSUE #53: Temporary executable break hooks
My program generates executable at runtime in `/tmp`, because the original is proprietary and I can't distribute a modified version. However, since `/tmp` is outside of the AppImage's root, the hooks remove all the linker variables, which breaks the program. Any ideas on how to fix this? My current idea is a `APPRUN_FORCE_BUNDLE_RUNTIME` environmental variable that a program can set.

### PR DESCRIPTION
**Pull request by TheBrokenRail**
Fixes #53

This is my suggested fix to the above issue, it adds an environmental variable that tells `libapprun_hooks.so` to assume the target executable is located in the AppImage.

### CODE REVIEW

**Comment by probonopd** [comment]
Please also think about documentation.

Speaking from experience, special edge case workarounds like this end up buried deep in the code and a few years down the road no one knows anymore why they are there...

**Comment by TheBrokenRail** [comment]
> Please also think about documentation.
> 
> Speaking from experience, special edge case workarounds like this end up buried deep in the code and a few years down the road no one knows anymore why they are there...

I added documentation to `docs/USAGE.md`.

**Comment by azubieta** [comment]
I guess that we were working on the same topic but with different approaches. With this commit https://github.com/AppImageCrafters/AppRun/commit/707c4015543e171067b2b321de5724624b5b74b9 I added support for external modules (plug-ins, add-ons, whatever) which will be treated as part of the original bundle and will use the same runtime.

The use case is to allow applications installing extensions in the user home or somewhere else. It comes with this script to make such modules functional https://gist.github.com/azubieta/202c85f1f5a9e5c6be5cb066fcb2d5e2

**Comment by TheBrokenRail** [comment]
Thanks!

**Pull request closed without merging**
