### PR TITLE
Fix #51

### LINKED ISSUE #51: `libapprun_hooks.so` Can Break Programs By Setting Working Directory
https://github.com/AppImageCrafters/AppRun/blob/2496b3929090c58d05ecd2a50d34fbc8262eb64c/src/hooks/main_hook.c#L16

This line of code that runs right before `main` restores the working directory of the parent process. Normally, this works fine. The calling process changes it's working directory so relative interpreters work, then it starts the program, then the hooks restore the current directory right before `main`.

However, there is an issue, if the child process changes its working directory for whatever reason inside of a `__attribute__((constructor))` function, that working directory is overwritten.

Suggested fix: Hook `chdir` and set a variable to `true` when `chdir` is called, only restore the original working directory if that variable is `false`.

### PR DESCRIPTION
**Pull request by TheBrokenRail**

### CODE REVIEW

**Review by azubieta — CHANGES_REQUESTED** [review]
I totally forgot about library constructors. I guess that `apprun_restore_workdir_if_needed` would be better in the `libapprun_hooks` constructor as it will be the first thing executed in the target applications.

**Comment by TheBrokenRail** [comment]
My reasoning for making it a global variable was that if something else modifies `LD_PRELOAD`, it would still keep track of `chdir` calls and handle appropriately even if `libapprun_hooks.so` isn't the first thing loaded. I'll definitely change `apprun_restore_workdir_if_needed` to run in a constructor function instead of the `main` hook though.

**Comment by azubieta** [comment]
If LD_PRELOAD is changed they can hook things before ours and change the working directory by the must restore it otherwise the app may fail. I guess that it's they responsibility to fix things. 

Let's divide this PR in two:
- One replacing the main function hook with the constructor
- Other to do the chdir modification (there we could continue the discussion)

**Comment by TheBrokenRail** [comment]
> If LD_PRELOAD is changed they can hook things before ours and change the working directory by the must restore it otherwise the app may fail. I guess that it's they responsibility to fix things.
> 
> Let's divide this PR in two:
> 
>     * One replacing the main function hook with the constructor
> 
>     * Other to do the chdir modification (there we could continue the discussion)

The only other things done in the `main` hook is debug logging that `main` has been called, so I don't think it needs to be switched completely into a constructor function, only the `chdir` stuff. For now, I'll just get rid of the global variable.

**Comment by azubieta** [comment]
Seems good! Thanks !

**Pull request merged**
